# Generated by Django 4.2.3 on 2023-09-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("customer_user_name", models.CharField(max_length=150)),
                ("customer_first_name", models.CharField(max_length=200)),
                ("customer_last_name", models.CharField(max_length=200)),
                (
                    "customer_avatar",
                    models.ImageField(blank=True, upload_to="profiles"),
                ),
                (
                    "customer_gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "country",
                    models.CharField(choices=[("India", "India")], max_length=200),
                ),
                ("phone", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Aizawl", "Aizawl"),
                            ("Agartala", "Agartala"),
                            ("Amaravati", "Amaravati"),
                            ("Bengaluru", "Bengaluru"),
                            ("Bhubaneswar", "Bhubaneswar"),
                            ("Bhopal", "Bhopal"),
                            ("Chandigarh", "Chandigarh"),
                            ("Dispur", "Dispur"),
                            ("Dehradun", "Dehradun"),
                            ("Gairsain", "Gairsain"),
                            ("Gandhinagar", "Gandhinagar"),
                            ("Gangtok", "Gangtok"),
                            ("Hyderabad", "Hyderabad"),
                            ("Imphal", "Imphal"),
                            ("Itanagar", "Itanagar"),
                            ("Jaipur", "Jaipur"),
                            ("Kohima", "Kohima"),
                            ("Kolkata", "Kolkata"),
                            ("Lucknow", "Lucknow"),
                            ("Mumbai", "Mumbai"),
                            ("Patna", "Patna"),
                            ("Panaji", "Panaji"),
                            ("Port Blair", "Port Blair"),
                            ("Raipur", "Raipur"),
                            ("Ranchi", "Ranchi"),
                            ("Shimla", "Shimla"),
                            ("Shillong", "Shillong"),
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh", "Arunachal Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West-Bengal", "West-Bengal"),
                        ],
                        max_length=200,
                    ),
                ),
                ("pincode", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("otp", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "activation_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
