# Generated by Django 4.2.3 on 2023-09-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="customer_avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="customer_first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="customer_gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="customer_last_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="user",
            name="state",
        ),
    ]
