# Generated by Django 4.2.3 on 2023-10-02 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="avatar",
        ),
    ]
