# Generated by Django 4.2.3 on 2023-09-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_address_remove_user_city_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="customer_user_name",
            new_name="user_name",
        ),
    ]
