# Generated by Django 4.2.3 on 2023-10-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_customer_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="profiles"),
        ),
    ]
