# Generated by Django 4.2.3 on 2023-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="activation_key",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.AddField(
            model_name="user",
            name="email_token",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
