# Generated by Django 4.2.3 on 2023-09-16 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_customer_user_name_user_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("avatar", models.ImageField(blank=True, upload_to="profiles")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Others", "Others"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "country",
                    models.CharField(choices=[("India", "India")], max_length=200),
                ),
                ("phone", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Aizawl", "Aizawl"),
                            ("Agartala", "Agartala"),
                            ("Amaravati", "Amaravati"),
                            ("Bengaluru", "Bengaluru"),
                            ("Bhubaneswar", "Bhubaneswar"),
                            ("Bhopal", "Bhopal"),
                            ("Chandigarh", "Chandigarh"),
                            ("Dispur", "Dispur"),
                            ("Dehradun", "Dehradun"),
                            ("Gairsain", "Gairsain"),
                            ("Gandhinagar", "Gandhinagar"),
                            ("Gangtok", "Gangtok"),
                            ("Hyderabad", "Hyderabad"),
                            ("Imphal", "Imphal"),
                            ("Itanagar", "Itanagar"),
                            ("Jaipur", "Jaipur"),
                            ("Kohima", "Kohima"),
                            ("Kolkata", "Kolkata"),
                            ("Lucknow", "Lucknow"),
                            ("Mumbai", "Mumbai"),
                            ("Patna", "Patna"),
                            ("Panaji", "Panaji"),
                            ("Port Blair", "Port Blair"),
                            ("Raipur", "Raipur"),
                            ("Ranchi", "Ranchi"),
                            ("Shimla", "Shimla"),
                            ("Shillong", "Shillong"),
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            (
                                "Andaman and Nicobar Islands",
                                "Andaman and Nicobar Islands",
                            ),
                            ("Andhra Pradesh", "Andhra Pradesh"),
                            ("Arunachal Pradesh", "Arunachal Pradesh"),
                            ("Assam", "Assam"),
                            ("Bihar", "Bihar"),
                            ("Chhattisgarh", "Chhattisgarh"),
                            ("Goa", "Goa"),
                            ("Gujarat", "Gujarat"),
                            ("Haryana", "Haryana"),
                            ("Himachal Pradesh", "Himachal Pradesh"),
                            ("Jharkhand", "Jharkhand"),
                            ("Karnataka", "Karnataka"),
                            ("Kerala", "Kerala"),
                            ("Madhya Pradesh", "Madhya Pradesh"),
                            ("Maharashtra", "Maharashtra"),
                            ("Manipur", "Manipur"),
                            ("Meghalaya", "Meghalaya"),
                            ("Mizoram", "Mizoram"),
                            ("Nagaland", "Nagaland"),
                            ("Odisha", "Odisha"),
                            ("Punjab", "Punjab"),
                            ("Rajasthan", "Rajasthan"),
                            ("Sikkim", "Sikkim"),
                            ("Tamil Nadu", "Tamil Nadu"),
                            ("Telangana", "Telangana"),
                            ("Tripura", "Tripura"),
                            ("Uttar Pradesh", "Uttar Pradesh"),
                            ("Uttarakhand", "Uttarakhand"),
                            ("West-Bengal", "West-Bengal"),
                        ],
                        max_length=200,
                    ),
                ),
                ("pincode", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
