# Generated by Django 4.2.3 on 2023-10-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_activation_key_remove_user_otp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="base_uid",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
