# Generated by Django 4.2.3 on 2023-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="profiles"),
        ),
    ]
