# Generated by Django 4.2.3 on 2023-10-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
