GENDER_CHOICES=(('Male','Male'),
                ('Female','Female'),
                ('Others','Others'))

STATE_CHOICES =(('Andaman and Nicobar Islands','Andaman and Nicobar Islands'),
                ('Andhra Pradesh','Andhra Pradesh'),
                ('Arunachal Pradesh','Arunachal Pradesh'),
                ('Assam','Assam'),
                ('Bihar','Bihar'),
                ('Chhattisgarh','Chhattisgarh'),
                ('Goa','Goa'),
                ('Gujarat','Gujarat'),
                ('Haryana','Haryana'),
                ('Himachal Pradesh','Himachal Pradesh'),
                ('Jharkhand','Jharkhand'),
                ('Karnataka','Karnataka'),
                ('Kerala','Kerala'),
                ('Madhya Pradesh','Madhya Pradesh'),
                ('Maharashtra','Maharashtra'),
                ('Manipur','Manipur'),
                ('Meghalaya','Meghalaya'),
                ('Mizoram','Mizoram'),
                ('Nagaland','Nagaland'),
                ('Odisha','Odisha'),
                ('Punjab','Punjab'),
                ('Rajasthan','Rajasthan'),
                ('Sikkim','Sikkim'),
                ('Tamil Nadu','Tamil Nadu'),
                ('Telangana','Telangana'),
                ('Tripura','Tripura'),
                ('Uttar Pradesh','Uttar Pradesh'),
                ('Uttarakhand','Uttarakhand'),
                ('West Bengal','West Bengal'))

CITY_CHOICES =(('Adoni','Adoni'),
               ('Amaravati','Amaravati'),
               ('Anantapur','Anantapur'),
               ('Ara','Ara'),
               ('Ambikapur','Ambikapur'),
               ('Ahmadabad','Ahmadabad'),
               ('Amreli','Amreli'),
               ('Ambala','Ambala'),
               ('Anantnag','Anantnag'),
               ('Alappuzha','Alappuzha'),
               ('Ahmadnagar','Ahmadnagar'),
               ('Akola','Akola'),
               ('Amravati','Amravati'),
               ('Aurangabad','Aurangabad'),
               ('Aizawl','Aizawl'),
               ('Amritsar','Amritsar'),
               ('Abu','Abu'),
               ('Ajmer','Ajmer'),
               ('Alwar','Alwar'),
               ('Amer','Amer'),
               ('Arcot','Arcot'),
               ('Agartala','Agartala'),
               ('Agra','Agra'),
               ('Aligarh','Aligarh'),
               ('Amroha','Amroha'),
               ('Ayodhya','Ayodhya'),
               ('Azamgarh','Azamgarh'),
               ('Almora','Almora'),
               ('Alipore','Alipore'),
               ('Alipur Duar','Alipur Duar'),
               ('Asansol','Asansol'))

COUNTRY_CHOICES =(('India','India'),)