GENDER_CHOICES=(('Male','Male'),
                ('Female','Female'),
                ('Others','Others'))

STATE_CHOICES =(('Andaman and Nicobar Islands','Andaman and Nicobar Islands'),
                ('Andhra Pradesh','Andhra Pradesh'),
                ('Arunachal Pradesh','Arunachal Pradesh'),
                ('Assam','Assam'),
                ('Bihar','Bihar'),
                ('Chhattisgarh','Chhattisgarh'),
                ('Goa','Goa'),
                ('Gujarat','Gujarat'),
                ('Haryana','Haryana'),
                ('Himachal Pradesh','Himachal Pradesh'),
                ('Jharkhand','Jharkhand'),
                ('Karnataka','Karnataka'),
                ('Kerala','Kerala'),
                ('Madhya Pradesh','Madhya Pradesh'),
                ('Maharashtra','Maharashtra'),
                ('Manipur','Manipur'),
                ('Meghalaya','Meghalaya'),
                ('Mizoram','Mizoram'),
                ('Nagaland','Nagaland'),
                ('Odisha','Odisha'),
                ('Punjab','Punjab'),
                ('Rajasthan','Rajasthan'),
                ('Sikkim','Sikkim'),
                ('Tamil Nadu','Tamil Nadu'),
                ('Telangana','Telangana'),
                ('Tripura','Tripura'),
                ('Uttar Pradesh','Uttar Pradesh'),
                ('Uttarakhand','Uttarakhand'),
                ('West-Bengal','West-Bengal'))

CITY_CHOICES =(('Aizawl','Aizawl'),
               ('Agartala','Agartala'),
               ('Amaravati','Amaravati'),
               ('Bengaluru','Bengaluru'),
               ('Bhubaneswar','Bhubaneswar'),
               ('Bhopal','Bhopal'),
               ('Chandigarh','Chandigarh'),
               ('Dispur','Dispur'),
               ('Dehradun','Dehradun'),
               ('Gairsain','Gairsain'),
               ('Gandhinagar','Gandhinagar'),
               ('Gangtok','Gangtok'),
               ('Hyderabad','Hyderabad'),
               ('Imphal','Imphal'),
               ('Itanagar','Itanagar'),
               ('Jaipur','Jaipur'),
               ('Kohima','Kohima'),
               ('Kolkata','Kolkata'),
               ('Lucknow','Lucknow'),
               ('Mumbai','Mumbai'),
               ('Patna','Patna'),
               ('Panaji','Panaji'),
               ('Port Blair','Port Blair'),
               ('Raipur','Raipur'),
               ('Ranchi','Ranchi'),
               ('Shimla','Shimla'),
               ('Shillong','Shillong'),
               ('Thiruvananthapuram','Thiruvananthapuram'))

COUNTRY_CHOICES =(('India','India'),)