# Generated by Django 4.2.3 on 2023-09-16 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("title_1", models.CharField(max_length=150)),
                ("title_2", models.CharField(max_length=150)),
                ("title_3", models.CharField(max_length=150)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
