# Generated by Django 4.2.3 on 2023-09-17 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeMiddleBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("img_name", models.CharField(max_length=70)),
                (
                    "h_tag",
                    models.IntegerField(
                        choices=[
                            (1, "<h1>"),
                            (2, "<h2>"),
                            (3, "<h3>"),
                            (4, "<h4>"),
                            (5, "<h5>"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "div_class_tag",
                    models.CharField(
                        choices=[
                            ("wthree_banner_bottom_left_grid_pos", "left_grid_pos"),
                            ("wthree_banner_btm_pos1", "banner_btm_pos1"),
                            ("wthree_banner_btm_pos", "banner_btm_pos"),
                        ],
                        default="wthree_banner_bottom_left_grid_pos",
                        max_length=150,
                    ),
                ),
                ("title_1", models.CharField(blank=True, max_length=150, null=True)),
                ("title_2", models.CharField(blank=True, max_length=150, null=True)),
                ("title_3", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "i_tag_title_4",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomeSlider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("title_1", models.CharField(max_length=150)),
                ("title_2", models.CharField(max_length=150)),
                ("title_3", models.CharField(max_length=150)),
                ("img_slide_code", models.IntegerField(blank=True, null=True)),
                (
                    "url_button_link",
                    models.CharField(default="products", max_length=60),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
