# Generated by Django 4.2.3 on 2023-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="img_slide_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
