# Generated by Django 4.2.3 on 2023-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_slider_img_slide_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="img_slide_code",
            field=models.IntegerField(blank=True, default="", null=True),
        ),
    ]
