# Generated by Django 4.2.3 on 2023-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_slider_img_slide_code"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Slider",
            new_name="IndexSlider",
        ),
    ]
