# Generated by Django 4.2.3 on 2023-10-31 05:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_homemiddlebanner_i_tag_title_4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("telephone", models.IntegerField()),
                ("email", models.EmailField(max_length=200)),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField(max_length=2000)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
