# Generated by Django 4.2.3 on 2023-11-01 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_contactus"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=200)),
                ("calltous", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
