# Generated by Django 4.2.3 on 2023-09-16 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_indexslider_homeslider"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeMiddleBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("img_name", models.CharField(max_length=70)),
                ("h_tag", models.IntegerField(default=0)),
                ("title_1", models.CharField(blank=True, max_length=150, null=True)),
                ("title_2", models.CharField(blank=True, max_length=150, null=True)),
                ("title_3", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "i_tag_title_4",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="homeslider",
            name="img_slide_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
