# Generated by Django 4.2.3 on 2023-11-01 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_contactinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"verbose_name_plural": "contactinfo"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "contactus"},
        ),
        migrations.AlterModelOptions(
            name="homemiddlebanner",
            options={"verbose_name_plural": "homemiddlebanner"},
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={"verbose_name_plural": "homeslider"},
        ),
    ]
