# Generated by Django 4.2.3 on 2023-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_homemiddlebanner_alter_homeslider_img_slide_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="homemiddlebanner",
            name="div_class_tag",
            field=models.CharField(
                choices=[
                    (
                        "wthree_banner_bottom_left_grid_pos",
                        "wthree_banner_bottom_left_grid_pos",
                    ),
                    (
                        "wthree_banner_bottom_left_grid",
                        "wthree_banner_bottom_left_grid",
                    ),
                ],
                default="wthree_banner_bottom_left_grid_pos",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="homemiddlebanner",
            name="h_tag",
            field=models.IntegerField(
                choices=[("h1", 1), ("h2", 2), ("h3", 3), ("h4", 4), ("h5", 5)],
                default=0,
            ),
        ),
    ]
