# Generated by Django 4.2.3 on 2023-09-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_homemiddlebanner_div_class_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homemiddlebanner",
            name="h_tag",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
    ]
