# Generated by Django 4.2.3 on 2023-11-01 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_contactinfo_options_alter_contactus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"verbose_name_plural": "contact info"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "contact us"},
        ),
        migrations.AlterModelOptions(
            name="homemiddlebanner",
            options={"verbose_name_plural": "home middle banner"},
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={"verbose_name_plural": "home slider"},
        ),
    ]
