# Generated by Django 4.2.3 on 2023-11-01 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_alter_contactinfo_options_alter_contactus_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactinfo",
            old_name="calltous",
            new_name="call_to_us",
        ),
    ]
