# Generated by Django 4.2.3 on 2023-11-01 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_rename_calltous_contactinfo_call_to_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("list_info", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "About List",
            },
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"verbose_name_plural": "Contact Info"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="homemiddlebanner",
            options={"verbose_name_plural": "Home Middle Banner"},
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={"verbose_name_plural": "Home Slider"},
        ),
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("information", models.TextField(max_length=2000)),
                ("about_img", models.ImageField(upload_to="about")),
                (
                    "list_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.aboutlist",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contact Info",
            },
        ),
    ]
