# Generated by Django 4.2.3 on 2023-09-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_homemiddlebanner_div_class_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homemiddlebanner",
            name="div_class_tag",
            field=models.CharField(
                choices=[
                    ("wthree_banner_bottom_left_grid_pos", "left_grid_pos"),
                    ("wthree_banner_btm_pos1", "banner_btm_pos1"),
                    ("wthree_banner_btm_pos", "banner_btm_pos"),
                ],
                default="wthree_banner_bottom_left_grid_pos",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="homemiddlebanner",
            name="h_tag",
            field=models.IntegerField(
                choices=[
                    (1, "<h1>"),
                    (2, "<h2>"),
                    (3, "<h3>"),
                    (4, "<h4>"),
                    (5, "<h5>"),
                ],
                default=0,
            ),
        ),
    ]
