# Generated by Django 4.2.3 on 2023-11-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_aboutinfo_alter_aboutus_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutus",
            name="list_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
