# Generated by Django 4.2.3 on 2023-09-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_alter_homemiddlebanner_div_class_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeslider",
            name="url_button_link",
            field=models.CharField(default="products", max_length=60),
        ),
    ]
