# Generated by Django 4.2.3 on 2023-11-01 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_aboutus_list_info"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutinfo",
            options={"verbose_name_plural": "about info"},
        ),
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name_plural": "about us"},
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"verbose_name_plural": "contact info"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "contact us"},
        ),
        migrations.AlterModelOptions(
            name="homemiddlebanner",
            options={"verbose_name_plural": "home middle banner"},
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={"verbose_name_plural": "home slider"},
        ),
    ]
