# Generated by Django 4.2.3 on 2023-11-01 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_alter_aboutinfo_options_alter_aboutus_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutinfo",
            options={"verbose_name_plural": "About Info"},
        ),
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name_plural": "About Us"},
        ),
        migrations.AlterModelOptions(
            name="contactinfo",
            options={"verbose_name_plural": "Contact Info"},
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="homemiddlebanner",
            options={"verbose_name_plural": "Home Middle Banner"},
        ),
        migrations.AlterModelOptions(
            name="homeslider",
            options={"verbose_name_plural": "Home Slider"},
        ),
    ]
