# Generated by Django 4.2.3 on 2023-11-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_alter_aboutinfo_options_alter_aboutus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="about_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="about_us",
                to="base.aboutinfo",
            ),
        ),
    ]
