# Generated by Django 4.2.3 on 2023-11-06 08:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_alter_aboutus_about_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutTestimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_by", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.DateTimeField(auto_now=True)),
                ("testimonials_text", models.TextField(max_length=400)),
                ("testimonial_Writter", models.CharField(max_length=150)),
                (
                    "about_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_testimonial",
                        to="base.aboutinfo",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "About Testimonial",
            },
        ),
    ]
