# Generated by Django 4.2.3 on 2023-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_abouttestimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abouttestimonial",
            name="testimonial_Writter_category",
            field=models.CharField(default="Customer", max_length=100),
        ),
    ]
