# Generated by Django 4.2.3 on 2023-11-06 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0017_abouttestimonial_testimonial_writter_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abouttestimonial",
            name="about_info",
        ),
    ]
