# Generated by Django 4.2.3 on 2023-11-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_services_servicerowtexts_serviceimages_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicebigimage",
            options={"verbose_name_plural": "Service Big Image"},
        ),
        migrations.AlterModelOptions(
            name="serviceimages",
            options={"verbose_name_plural": "Service Images"},
        ),
        migrations.AlterModelOptions(
            name="servicerowtexts",
            options={"verbose_name_plural": "Service Row Texts"},
        ),
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name_plural": "Services"},
        ),
    ]
