name: Build Code


on: [push, pull_request]

jobs:
  build:
    environment:
      name: Testing Code using pytest

    env:
      DATABASE_NAME: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_NAME}}
      DATABASE_USER: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_PASSWORD}}
      DATABASE_HOST: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_HOST}}
      DATABASE_PORT: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_PORT}}
      DJANGO_SECRET_KEY: ${{secrets.ECOMMERCE_GLOCERY_SECRET_KEY}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.ECOMMERCE_GLOCERY_DATABASE_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: pulling codes from repository
        uses: actions/checkout@v4.1.6
        
      - name: Install python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11.4'
      
      - name: update pip
        run: python -m pip install --upgrade pip

      - name: Install all the dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Automate test codes with pytest
        run: |
          pip install pytest
          pytest
      
