# Generated by Django 4.2.3 on 2023-09-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories",
            old_name="category_link",
            new_name="slug",
        ),
        migrations.RenameField(
            model_name="subcategories",
            old_name="subcategory_link",
            new_name="slug",
        ),
    ]
