# Generated by Django 4.2.3 on 2023-09-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_category_link_categories_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_categories",
                to="products.categories",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="subcategories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_subcategories",
                to="products.subcategories",
            ),
        ),
    ]
