# Generated by Django 4.2.3 on 2023-09-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_products_categories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="product_slug",
            new_name="slug",
        ),
    ]
