# Generated by Django 4.2.3 on 2023-09-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_product_slug_products_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="subcategories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.subcategories"
            ),
        ),
    ]
