# Generated by Django 4.2.3 on 2023-09-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_products_subcategories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="subcategories",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.subcategories",
            ),
        ),
    ]
