# Generated by Django 4.2.3 on 2023-09-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="homeTag",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="tags",
            name="innerTag",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
