# Generated by Django 4.2.3 on 2023-09-18 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_tags_hometag_alter_tags_innertag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tags",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_tags",
                to="products.products",
            ),
        ),
    ]
