# Generated by Django 4.2.3 on 2023-09-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_tags_products"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
