# Generated by Django 4.2.3 on 2023-09-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_tags_products_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
        migrations.RenameModel(
            old_name="Subcategories",
            new_name="Subcategory",
        ),
    ]
