# Generated by Django 4.2.3 on 2023-09-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0012_rename_categories_category_rename_products_product_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tags",
            new_name="Tag",
        ),
    ]
