# Generated by Django 4.2.3 on 2023-09-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_rename_tags_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_rating",
            field=models.IntegerField(default=0),
        ),
    ]
