# Generated by Django 4.2.3 on 2023-10-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_alter_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping_charges",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
