# Generated by Django 4.2.3 on 2023-10-20 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_cart_shipping_charges"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="shipping_charges",
        ),
    ]
