# Generated by Django 4.2.3 on 2023-11-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_remove_cart_coupon_remove_cart_is_paid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalpricecoupon",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.cart",
            ),
        ),
    ]
