# Generated by Django 4.2.3 on 2024-02-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0029_gsteighteenpercent_gstfivepercent_gsttwelvepercent_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gsteighteenpercent",
            name="gstzero_percent",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.gstzeropercent",
            ),
        ),
        migrations.AddField(
            model_name="gstfivepercent",
            name="gstzero_percent",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.gstzeropercent",
            ),
        ),
        migrations.AddField(
            model_name="gsttwelvepercent",
            name="gstzero_percent",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="products.gstzeropercent",
            ),
        ),
    ]
