# Generated by Django 4.2.3 on 2024-02-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0034_remove_cart_is_paid_orderplaced_is_payment_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderplaced",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accepted", "Accepted"),
                    ("Packed", "Packed"),
                    ("On The Way", "On The Way"),
                    ("Delivered", "Delivered"),
                    ("Cancel", "Cancel"),
                ],
                default="Accepted",
                max_length=50,
            ),
        ),
    ]
