# Generated by Django 4.2.3 on 2024-02-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_remove_user_is_verified_alter_user_is_active"),
        ("products", "0035_alter_orderplaced_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderplaced",
            name="customer",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="account.customer",
            ),
        ),
    ]
