# Generated by Django 4.2.3 on 2024-02-16 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_alter_orderplaced_customer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderplaced",
            options={"verbose_name_plural": "Ordered Items"},
        ),
        migrations.AlterModelOptions(
            name="producttype",
            options={"verbose_name_plural": "Product Types"},
        ),
    ]
