# Generated by Django 4.2.3 on 2024-02-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0038_alter_orderplaced_options_alter_producttype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
